#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }


if ARGV.empty?
  say("(Help) run as: './mainteance_tracker' with args: new, add, etc.\n")
  exit
end

if ARGV.length == 2 and ARGV[0] == "update" and ARGV[1] == "miles"
  MileagesController.new.update_miles
elsif ARGV.length == 2 and ARGV[0] == "new" and ARGV[1] == "car"
  CarsController.new.new_car
elsif ARGV.length == 2 and ARGV[0] == "edit" and ARGV[1] == "car"
  cars_controller = CarsController.new
  cars_controller
elsif ARGV.length == 1 and ARGV[0] == "new"
  say("(Help) Please supply argument 'car' or 'job' after 'new' command")
else
  "ERROR MESSAGE HERE!\n"
end
