production:
  adapter: sqlite3
  database: db/maintenance_tracker_production.sqlite
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/maintenance_tracker_test.sqlite
  pool: 5
  timeout: 5000
